apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: openshiftxrays.charts.helm.k8s.io
spec:
  group: charts.helm.k8s.io
  names:
    kind: OpenshiftXray
    listKind: OpenshiftXrayList
    plural: openshiftxrays
    singular: openshiftxray
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
